app = "servidor-lac-app"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 5055
  protocol = "tcp"

  [[services.ports]]
    port = 5055
    
[[services]]
  internal_port = 5055
  protocol = "tcp"

  [[services.ports]]
    port = 5055
